### ISSUE TITLE
Limit order (buy) fails

### ISSUE THREAD

**Issue by LaoTszy** [Zarathustra2/TradeRepublicApi#22]
Limit order (buy), e.g:

    await tr.limit_order(order_id, 'DE0007037129', 'buy', '1', '21.78', 'gfd')

fails with

Unrecognized state  E  data  ['{"errors":[{"errorCode":"JSON_PARSE_ERROR","errorField":null,"errorMessage":"Subscription', 'payload', '<{\\"type\\":\\"simpleCreateOrder\\",\\"clientProcessId\\":\\" < some generated uuid > \\",\\"warningsShown\\":[\\"userExperience\\"],\\"acceptedWarnings\\":[\\"userExperience\\"],\\"parameters\\":{\\"instrumentId\\":\\"DE0007037129\\",\\"exchangeId\\":\\"LSX\\",\\"expiry\\":{\\"type\\":\\"gfd\\"},\\"limit\\":\\"21.78\\",\\"mode\\":\\"limit\\",\\"size\\":\\"1\\",\\"type\\":\\"buy\\"},\\"token\\":\\" < the very long token > \\"}>', 'validation', 'failed","meta":{"source":"MAPPER"}}]}']

This json above really looks funny with "errorMessage" value looking like a fragment of the payload without its head and tail parts.

**Comment by Zarathustra2** [comment]
What if you use the previous commit before the merge?

**Comment by LaoTszy** [comment]
I have indeed used the version preceding the merge. The error looks a bit different now with an exception thrown in TRApi.start. The content of the message is still the same though:

Traceback (most recent call last):
  File "using_tr.py", line 25, in history
    await tr.start()
  File "api.py", line 349, in start
    raise TRapiExcServerErrorState(f"Error during server access\n\tServer-side Object probably expired...\n\t{sErr}")
trapi.api.TRapiExcServerErrorState: Error during server access
	Server-side Object probably expired...
	ERROR state: E data: ['{"errors":[{"errorCode":"JSON_PARSE_ERROR","errorField":null,"errorMessage":"Subscription', 'payload', '<{\\"type\\":\\"simpleCreateOrder\\",\\"clientProcessId\\":\\" <uuid> \\",\\"warningsShown\\":[\\"userExperience\\"],\\"acceptedWarnings\\":[\\"userExperience\\"],\\"parameters\\":{\\"instrumentId\\":\\"DE0007037129\\",\\"exchangeId\\":\\"LSX\\",\\"expiry\\":{\\"type\\":\\"gfd\\"},\\"limit\\":\\"35.85\\",\\"mode\\":\\"limit\\",\\"size\\":\\"1\\",\\"type\\":\\"buy\\"},\\"token\\":\\" <token> \\"}>', 'validation', 'failed","meta":{"source":"MAPPER"}}]}']
python-BaseException

**Comment by Zarathustra2** [comment]
hmmm interesting. Not sure if I find the time to debug it as I don't use TR really

**Comment by LaoTszy** [comment]
How did you come up with this API? I've tried to look at the the web application network exchange: it looks pretty different to me.

**Comment by Jeffote** [comment]
is there an update to this issue?

**Comment by deepbeat** [comment]
hello there, having the same issue. Anyone working on this? And if not, how and with what tools did you reverse engineer this API exactly?

**Comment by deepbeat** [comment]
Solved it. It still works with the given code. You just need to give a well-formated uuid as id. Otherwise you get this misleading JSON_PARSE_ERROR from above.

However, I am still very interested in this open question: how and with what tools did you reverse engineer this API exactly?

**Comment by LudwigJMarx** [comment]
This is solved, and there are **two** separate causes for that
`JSON_PARSE_ERROR`. The report at the top has both at once, which is why it
was hard to pin down.

I found them by sending payload variants **without a session**. Without a
token the server refuses the request for the missing token rather than for
its shape, so nothing can be executed and the two failure modes can be told
apart safely. Checked against the live API in August 2026:

| payload | result |
| --- | --- |
| numbers + valid uuid | passes validation |
| `size` / `limit` as **strings** | `validation failed` |
| `clientProcessId` not a **uuid** | `validation failed` |
| both, as in the report above | `validation failed` |

The call in the first post,

```python3
await tr.limit_order(order_id, 'DE0007037129', 'buy', '1', '21.78', 'gfd')
```

passes `'1'` and `'21.78'` as strings, and they go into the payload
unchanged. @deepbeat is right about the id - a uuid fixes one of the two, and
presumably the values were already numbers on their side. A uuid without
dashes is accepted too, so that part is not strict.

## The payload itself is fine

It is still the right one. On a real account `simpleCreateOrder` reaches the
order engine and is processed - my attempt came back refused for a business
reason, not for its shape:

```json
{"status": "failed",
 "message": "Insufficient funds for this operation.",
 "error": {"code": "cashMissing", "details": {"exchangeId": "LSXCS", "...": "..."}}}
```

Two things worth knowing if you build on this:

**A rejection comes back as a normal answer, not as an error state.** Look at
`status`; "no exception" does not mean the order was placed.

**`details.exchangeId` is not what was sent.** `LSX` comes back as `LSXCS`.

## Something else that breaks order calls

While testing this I hit a different failure that looks unrelated but bites
exactly here. The library subscribes and never unsubscribes - there was no
`unsub` at all - so every topic ever subscribed on the connection keeps
sending updates. A price update from an earlier `priceForOrder` arrived
between sending `simpleCreateOrder` and its answer, and the read loop died
with `KeyError` in `decode_updates` **after** the order had already gone out.

If you have seen order calls end in a traceback with the order in an unclear
state, that may be this rather than the payload.

## Fixed in #42

`simple_create_order` now converts the numbers and checks the id before the
request goes out, and reports which field is wrong instead of leaving you
with the server quoting your payload back. Passing `None` as the order id
generates one. Subscriptions are ended properly, so a stale update cannot
take down an unrelated call any more.

#42 also adds `priceForOrder` and `availableSize`. Note that #42 sits on top
of #37 and #39 - the websocket handshake and the login are both broken
against the current API, so nothing works before those go in.

What is still untested: the answer to an order that actually goes through. I
only got as far as a refusal, and finding out more means placing real orders.
