### ISSUE TITLE
sms verification

### ISSUE THREAD

**Issue by dakonga** [Zarathustra2/TradeRepublicApi#8]
After running timelineExporter.py i got a verification sms. How to handle it?

first run:
Traceback (most recent call last):
  File "timelineExporter.py", line 11, in <module>
    tr.login()
  File "../trapi/api.py", line 83, in login
    self.register_new_device()
  File "../trapi/api.py", line 50, in register_new_device
    self.signing_key.get_verifying_key().to_string("uncompressed")
TypeError: to_string() takes 1 positional argument but 2 were given

next run:
Traceback (most recent call last):
  File "timelineExporter.py", line 11, in <module>
    tr.login()
  File "../trapi/api.py", line 83, in login
    self.register_new_device()
  File "../trapi/api.py", line 46, in register_new_device
    processId = r.json()["processId"]
KeyError: 'processId'

**Comment by nickerber** [comment]
Obviously you did a mistake. I got the same error after I entered the wrong phone number in environment.py. Check the docs if you did all steps correctly, afterwards an sms will be sent and the command line asks you to "Enter your token".
